version: '3.8'

networks:
    project-network:
        name: project-network

services:
    php:
        build: ./docker/php
        container_name: php
        restart: unless-stopped
        volumes: 
            - ./:/var/www/html
        networks: 
            - project-network

    nginx: 
        image: crmsolucoes/nginx-stable-alpine:latest
        container_name: nginx
        restart: unless-stopped
        depends_on:
            - php
            - phpmyadmin
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/log:/var/log/nginx
            - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - project-network

    artisan:
        build: ./docker/php
        container_name: artisan
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        entrypoint: ["php", "artisan"]
        networks:
            - project-network

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - project-network
    
    npm:
        image: node:12
        container_name: npm
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        entrypoint: ["npm"]
        networks:
            - project-network

    mysql:
        image: 'mysql/mysql-server:8.0'
        restart: unless-stopped
        container_name: mysql
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - project-network
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin
        depends_on:
            - mysql
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        networks:
            - project-network